# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eloquently
email: eric@eloquent.ly
description: > # this means to ignore newlines until "baseurl:"
  Eloquently web developer recuriting and workshops.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eloquent.ly" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
highlighter: none
disable_indented_code_blocks: true

exclude:
    - Gemfile
    - Gemfile.lock
    - Guardfile
